"""lookup indexes

Revision ID: 0003_lookup_indexes
Revises: 0002_runtime_indexes
Create Date: 2026-04-11 19:22:43.639377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from ml_service.db.models import DB_SCHEMA

# revision identifiers, used by Alembic.
revision: str = '0003_lookup_indexes'
down_revision: Union[str, Sequence[str], None] = '0002_runtime_indexes'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ml_artifacts_job_id'), 'artifacts', ['job_id'], unique=False, schema=DB_SCHEMA)
    op.create_index(op.f('ix_ml_artifacts_kind'), 'artifacts', ['kind'], unique=False, schema=DB_SCHEMA)
    op.create_index(op.f('ix_ml_artifacts_project_id'), 'artifacts', ['project_id'], unique=False, schema=DB_SCHEMA)
    op.create_index(op.f('ix_ml_jobs_idempotency_key'), 'jobs', ['idempotency_key'], unique=False, schema=DB_SCHEMA)
    op.create_index(op.f('ix_ml_jobs_project_id'), 'jobs', ['project_id'], unique=False, schema=DB_SCHEMA)
    op.create_index(op.f('ix_ml_jobs_request_id'), 'jobs', ['request_id'], unique=False, schema=DB_SCHEMA)
    op.create_index(op.f('ix_ml_jobs_status'), 'jobs', ['status'], unique=False, schema=DB_SCHEMA)
    op.create_index(op.f('ix_ml_jobs_type'), 'jobs', ['type'], unique=False, schema=DB_SCHEMA)
    op.create_index(op.f('ix_ml_projects_project_type'), 'projects', ['project_type'], unique=False, schema=DB_SCHEMA)
    op.create_index(op.f('ix_ml_projects_status'), 'projects', ['status'], unique=False, schema=DB_SCHEMA)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ml_projects_status'), table_name='projects', schema=DB_SCHEMA)
    op.drop_index(op.f('ix_ml_projects_project_type'), table_name='projects', schema=DB_SCHEMA)
    op.drop_index(op.f('ix_ml_jobs_type'), table_name='jobs', schema=DB_SCHEMA)
    op.drop_index(op.f('ix_ml_jobs_status'), table_name='jobs', schema=DB_SCHEMA)
    op.drop_index(op.f('ix_ml_jobs_request_id'), table_name='jobs', schema=DB_SCHEMA)
    op.drop_index(op.f('ix_ml_jobs_project_id'), table_name='jobs', schema=DB_SCHEMA)
    op.drop_index(op.f('ix_ml_jobs_idempotency_key'), table_name='jobs', schema=DB_SCHEMA)
    op.drop_index(op.f('ix_ml_artifacts_project_id'), table_name='artifacts', schema=DB_SCHEMA)
    op.drop_index(op.f('ix_ml_artifacts_kind'), table_name='artifacts', schema=DB_SCHEMA)
    op.drop_index(op.f('ix_ml_artifacts_job_id'), table_name='artifacts', schema=DB_SCHEMA)
    # ### end Alembic commands ###
